/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeneticOptimizationSettingsPanel.java
 *
 * Created on Mar 19, 2012, 4:21:50 PM
 */
package org.activeintel.gephi.network.optimization.genetic.ui;

/**
 *
 * @author neil
 */
public class GeneticOptimizationSettingsPanel extends javax.swing.JPanel {

    /** Creates new form GeneticOptimizationSettingsPanel */
    public GeneticOptimizationSettingsPanel() {
        initComponents();
    }
    
    
    public int getStagnationSteps(){
        return Integer.valueOf(stagnationStepsTxtFld.getText());
    }
    
    
    public float getEliteRatio(){
        return Float.valueOf(elitisimRatioTxtFld.getText());
    }
    
    
    public int getEliteCount(){
        return Math.round(getEliteRatio() * getPopulationSize());
    }
    
    
    public int getPopulationSize(){
        return Integer.valueOf(populationSizeTxtFld.getText());
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        populationSizeTxtFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        elitisimRatioTxtFld = new javax.swing.JTextField();
        stagnationStepsTxtFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pMutationTxtFld = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(null);
        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GeneticOptimizationSettingsPanel.class, "GeneticOptimizationSettingsPanel.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(GeneticOptimizationSettingsPanel.class, "GeneticOptimizationSettingsPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(GeneticOptimizationSettingsPanel.class, "GeneticOptimizationSettingsPanel.jLabel2.text")); // NOI18N

        populationSizeTxtFld.setText(org.openide.util.NbBundle.getMessage(GeneticOptimizationSettingsPanel.class, "GeneticOptimizationSettingsPanel.populationSizeTxtFld.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(GeneticOptimizationSettingsPanel.class, "GeneticOptimizationSettingsPanel.jLabel3.text")); // NOI18N

        elitisimRatioTxtFld.setText(org.openide.util.NbBundle.getMessage(GeneticOptimizationSettingsPanel.class, "GeneticOptimizationSettingsPanel.elitisimRatioTxtFld.text")); // NOI18N

        stagnationStepsTxtFld.setText(org.openide.util.NbBundle.getMessage(GeneticOptimizationSettingsPanel.class, "GeneticOptimizationSettingsPanel.stagnationStepsTxtFld.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(GeneticOptimizationSettingsPanel.class, "GeneticOptimizationSettingsPanel.jLabel4.text")); // NOI18N

        pMutationTxtFld.setText(org.openide.util.NbBundle.getMessage(GeneticOptimizationSettingsPanel.class, "GeneticOptimizationSettingsPanel.pMutationTxtFld.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(populationSizeTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pMutationTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(elitisimRatioTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 244, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stagnationStepsTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(populationSizeTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(pMutationTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(elitisimRatioTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(stagnationStepsTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField elitisimRatioTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField pMutationTxtFld;
    private javax.swing.JTextField populationSizeTxtFld;
    private javax.swing.JTextField stagnationStepsTxtFld;
    // End of variables declaration//GEN-END:variables

    double getPMutation() {
        return Double.valueOf(pMutationTxtFld.getText());
    }
}
