/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NetworkCriteriaPanel.java
 *
 * Created on Mar 21, 2012, 12:35:39 PM
 */
package org.activeintel.gephi.network.optimization.genetic.ui;

import java.util.Dictionary;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import java.util.Properties;
import org.activeintel.network.optimization.algorithms.SubGraphEvaluator;

/**
 *
 * @author neil
 */
public class NetworkCriteriaPanel extends javax.swing.JPanel {

    /** Creates new form NetworkCriteriaPanel */
    public NetworkCriteriaPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        subNetInDegreeUtilityTxtFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        subNetOutDegreeUtilityTxtFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        netInDegreeUtilityTxtFld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        netOutDegreeUtilityTxtFld = new javax.swing.JTextField();
        edgeWeightUtilityFactorTxtFld = new javax.swing.JTextField();
        clusterVariabilityUtilityFactor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(null);
        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.jLabel1.text")); // NOI18N

        jPanel1.setBackground(null);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.jPanel1.border.title"))); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.jLabel2.text")); // NOI18N

        subNetInDegreeUtilityTxtFld.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.subNetInDegreeUtilityTxtFld.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.jLabel3.text")); // NOI18N

        subNetOutDegreeUtilityTxtFld.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.subNetOutDegreeUtilityTxtFld.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.jLabel5.text")); // NOI18N

        netInDegreeUtilityTxtFld.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.netInDegreeUtilityTxtFld.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.jLabel6.text")); // NOI18N

        netOutDegreeUtilityTxtFld.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.netOutDegreeUtilityTxtFld.text")); // NOI18N

        edgeWeightUtilityFactorTxtFld.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.edgeWeightUtilityFactorTxtFld.text")); // NOI18N

        clusterVariabilityUtilityFactor.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.clusterVariabilityUtilityFactor.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.jLabel7.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(NetworkCriteriaPanel.class, "NetworkCriteriaPanel.jButton1.text")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel2)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(edgeWeightUtilityFactorTxtFld, 0, 0, Short.MAX_VALUE)
                            .add(netOutDegreeUtilityTxtFld, 0, 0, Short.MAX_VALUE)
                            .add(netInDegreeUtilityTxtFld, 0, 0, Short.MAX_VALUE)
                            .add(subNetOutDegreeUtilityTxtFld)
                            .add(subNetInDegreeUtilityTxtFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(clusterVariabilityUtilityFactor)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(subNetInDegreeUtilityTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(subNetOutDegreeUtilityTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(netInDegreeUtilityTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(netOutDegreeUtilityTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(edgeWeightUtilityFactorTxtFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(clusterVariabilityUtilityFactor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addContainerGap(286, Short.MAX_VALUE))
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clusterVariabilityUtilityFactor;
    private javax.swing.JTextField edgeWeightUtilityFactorTxtFld;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField netInDegreeUtilityTxtFld;
    private javax.swing.JTextField netOutDegreeUtilityTxtFld;
    private javax.swing.JTextField subNetInDegreeUtilityTxtFld;
    private javax.swing.JTextField subNetOutDegreeUtilityTxtFld;
    // End of variables declaration//GEN-END:variables

    
}
